/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cmiDellConnect;

public class App {

private String URL =  "" ;

    public static void main(String[] args) {
        System.out.println("Hello World");
    }

}
